---
- name: Download distribution
  get_url:
    url: "{{ download_url }}"
    dest: /opt/{{ dist_file }}
    checksum: "{{ dist_checksum }}"

- name: Extract archive
  unarchive: src=/opt/{{ dist_file }} dest=/opt copy=no

- name: Make symlink
  file:
    src: "{{ install_dir }}"
    dest: "{{ install_dir_symlink }}"
    state: link

- name: Install unit configuration file
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: 0755
  with_items:
    - kafka.service
    - zookeeper.service